name: I18n Process Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-i18n-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: 'maven'

    - name: Build Fluent i18n
      run: mvn -B clean install -DskipTests

    - name: Test message extraction
      run: |
        cd fluent-i18n-examples/simple-web-app
        mvn fluent-i18n:extract
        echo "Extraction completed"

    - name: Test message compilation
      run: |
        cd fluent-i18n-examples/simple-web-app
        mvn fluent-i18n:compile
        echo "Compilation completed"

    - name: Verify generated files
      run: |
        cd fluent-i18n-examples/simple-web-app
        ls -la src/main/resources/i18n/
        echo "Generated files:"
        find src/main/resources/i18n/ -name "*.po" -o -name "*.json" -o -name "*.properties" | head -10

    - name: Upload generated files
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: i18n-generated-files
        path: fluent-i18n-examples/simple-web-app/src/main/resources/i18n/
        retention-days: 7 